language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
deploy:
  - provider: script
    script: 'make doc'
    deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/_build/html/
        on:
            branch: master
  - provider: script
    script: 'make test'
    after_success:
      - 'python-codacy-coverage -r coverage.xml'
