language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
jobs:
    include:
        - stage: pytest
          script: 'make test'
          after_success:
            - 'python-codacy-coverage -r coverage.xml'
        - stage: sphinx
          script: 'make doc'
          deploy:
              provider: pages
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              keep-history: true
              local-dir: docs/build/html/
              on:
                  branch: master
