sudo: false
language: python
python:
  - '3.6'
env:
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
jobs:
    include:
        - script: 'make test'
          after_success:
            - 'python-codacy-coverage -r coverage.xml'
        - script: 'make doc'
          deploy:
              provider: pages
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              keep-history: true
              local-dir: docs/_build/html/
              on:
                  branch: master
