language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
jobs:
    include:
        - script: 'make test'
          after_success:
            - 'python-codacy-coverage -r coverage.xml'
        - script: 'make doc'
          deploy:
              provider: pages
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              keep-history: true
              local-dir: docs/_build/html/
              on:
                  branch: master
