version: '3.1'

services:
  mongo:
    image: mongo
    restart: on-failure:5
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: db
    volumes:
        - ./docker-scripts:/docker-entrypoint-initdb.d/
    ports:
        - 27017:27017

